# Kafka Admin SSL Configuration
security.protocol=SSL

# SSL Truststore Configuration
ssl.truststore.location=./kafka.client.truststore.jks
ssl.truststore.password=changeit

# SSL Keystore Configuration (client certificate)
ssl.keystore.location=./kafka.client.keystore.jks
ssl.keystore.password=changeit
ssl.key.password=changeit

# SSL Keystore Configuration (client certificate)
ssl.keystore.alias=user

# SSL Protocol
ssl.protocol=TLSv1.2
