# Kafka Admin SSL Configuration
security.protocol=SSL

# SSL Keystore Configuration (admin certificate)
ssl.keystore.location=./kafka.admin.keystore.p12
ssl.keystore.password=changeit
ssl.key.password=changeit

# SSL Keystore Configuration (admin certificate)
ssl.keystore.alias=admin

# SSL Protocol
ssl.protocol=TLSv1.2
