# Kafka Admin SSL Configuration
security.protocol=SSL

# SSL Keystore Configuration (client certificate)
ssl.keystore.location=./kafka.client.keystore.p12
ssl.keystore.password=changeit
ssl.key.password=changeit

# SSL Keystore Configuration (client certificate)
ssl.keystore.alias=client

# SSL Protocol
ssl.protocol=TLSv1.2
